/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface TestText {}
  interface TestTextAttributes extends StencilHTMLAttributes {}

  interface UseFont {}
  interface UseFontAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'TestText': Components.TestText;
    'UseFont': Components.UseFont;
  }

  interface StencilIntrinsicElements {
    'test-text': Components.TestTextAttributes;
    'use-font': Components.UseFontAttributes;
  }


  interface HTMLTestTextElement extends Components.TestText, HTMLStencilElement {}
  var HTMLTestTextElement: {
    prototype: HTMLTestTextElement;
    new (): HTMLTestTextElement;
  };

  interface HTMLUseFontElement extends Components.UseFont, HTMLStencilElement {}
  var HTMLUseFontElement: {
    prototype: HTMLUseFontElement;
    new (): HTMLUseFontElement;
  };

  interface HTMLElementTagNameMap {
    'test-text': HTMLTestTextElement
    'use-font': HTMLUseFontElement
  }

  interface ElementTagNameMap {
    'test-text': HTMLTestTextElement;
    'use-font': HTMLUseFontElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
